spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderplacementdb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show_sql: true
  data:
    jdbc:
      dialect: postgresql
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

